---
title: "Projekt"
author: "Paulina Jasińska"
date: '2024-04-17'
output: html_document
---
```{r}
library(readr)
health <- read_csv("I:/Ekonometria/health.csv")
View(health)
library(tidyverse)
glimpse(health)
```

```{r}
health <- health %>% mutate(diabetes=as.factor(diabetes)) %>% 
mutate(smoker=as.factor(smoker))
summary(health)
```

```{r}
health %>%
  ggplot() +
  geom_histogram(mapping = aes(x=systolic), fill= "lightpink", color= "black")+
  theme_minimal()
```
```{r}
health %>%
  select(-systolic) %>%
  keep(is.numeric) %>%
  gather() %>%
  ggplot() +
  geom_histogram(mapping = aes(x=value, fill=key), color="black") + facet_wrap(~ key, scales = "free") +
  theme_minimal()
```
```{r}
cor(health[, c("systolic", "weight", "height", "bmi", "waist", "age", "fastfood")])
```
```{r}
health_mod1 <- lm(data = health, systolic~age)
summary(health_mod1)
```
```{r}
health_mod2 <- lm(data = health, systolic~.)
summary(health_mod2)
```
```{r}
mean(health_mod2$residuals)
```
```{r}
install.packages("olsrr")
library(olsrr)
```
```{r}
ols_plot_resid_hist(health_mod2)
```
```{r}
ols_plot_resid_fit(health_mod2)
```
```{r}
library(car)
durbinWatsonTest(health_mod2)
```
```{r}
ols_plot_cooksd_chart(health_mod2)
```
```{r}
health[1358,]
```
```{r}
summary(health)
```
```{r}
outlier_index <-
  as.numeric(unlist(ols_plot_cooksd_chart(health_mod2)$outliers[,"observation"]))
outlier_index
```
```{r}
summary(health[outlier_index,])
```

